mobile_base_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : ['wheel_left_1_joint', 'wheel_left_2_joint']
  right_wheel : ['wheel_right_1_joint', 'wheel_right_2_joint']
  publish_rate: 50.0 
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  wheel_separation: 0.676
  wheel_radius: 0.2

  # Velocity commands timeout [s], default 0.5
  key_vel_timeout: 0.25

  enable_odom_tf: False
